### ISSUE TITLE
Some dependency Issue are occurring in new build

### ISSUE THREAD

**Issue by MohitGupta12** [MohitGupta12/Dsa_Tracker#4]
You can deploy this in your local machine to access build logs

![Screenshot 2024-10-27 143837](https://github.com/user-attachments/assets/90392a3e-9def-4478-bae8-3425de478575)
![image_2024-10-27_144328193](https://github.com/user-attachments/assets/85cf3342-054c-4bd9-9fe6-fe0fbe6a6792)

**Comment by Harry101969** [comment]
I'll check this out!

**Comment by MohitGupta12** [comment]
I'll assign it to you
